<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" hash="1601053871">
    <data-source source="LOCAL" name="Django default" uuid="b77a4c47-7212-4c28-9bbb-016e93d69538">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/sati_django/hello_django/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:postgresql://127.0.0.1:5432/satiutfpr</jdbc-url>
      <explain-plan-config>
        <provider>com.intellij.database.plan.postgres.PostgresExplainPlanProvider</provider>
      </explain-plan-config>
    </data-source>
    <data-source source="LOCAL" name="Django default2" uuid="ae4dcaf8-ea49-4a88-9b9c-0fe8ac6147c7">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/sati_django/hello_django/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:$PROJECT_DIR$/sati_django/test.db</jdbc-url>
    </data-source>
  </component>
</project>